export const ProductsObj = [
  { code: "SCD0001", name: "SHAMPOO", stock: 0 },
  { code: "SCD0002", name: "ACONDICIONADOR", stock: 0 },
  { code: "SCD0003", name: "GEL DE BAÑO", stock: 0 },
  { code: "SCD0004", name: "Toallas Corporales ", stock: 0 },
  { code: "SCD0005", name: "Toallas de Mano", stock: 0 },
  { code: "SCD0006", name: "Tapetes de baño", stock: 0 },
  { code: "SCD0007", name: "Toalla Facial", stock: 0 },
  { code: "SCD0008", name: "Toallas de Alberca", stock: 0 },
  { code: "SCD0009", name: "Sabanas Individuales", stock: 0 },
  { code: "SCD0010", name: "Sábanas Cajon individuales", stock: 0 },
  { code: "SCD0011", name: "Protector Colchon Individual", stock: 0 },
  { code: "SCD0012", name: "Sábanas Lisa Matrimoniales", stock: 0 },
  { code: "SCD0013", name: "Sábanas Cajon Matrimonial ", stock: 0 },
  { code: "SCD0014", name: "Protector Colchon Matrimonial", stock: 0 },
  { code: "SCD0015", name: "Cobertor Matrimonial ", stock: 0 },
  { code: "SCD0016", name: "Sábanas planas Queen", stock: 0 },
  { code: "SCD0017", name: "Protector Colchon Queen", stock: 0 },
  { code: "SCD0018", name: "Inserto Queen", stock: 0 },
  { code: "SCD0019", name: "Duvet Queen ", stock: 0 },
  { code: "SCD0020", name: "Sábanas Lisa King ", stock: 0 },
  { code: "SCD0021", name: "Sábana cajon King ", stock: 0 },
  { code: "SCD0022", name: "Cobertor King ", stock: 0 },
  { code: "SCD0023", name: "Protector Colchon King ", stock: 0 },
  { code: "SCD0024", name: "Inserto King ", stock: 0 },
  { code: "SCD0025", name: "Duvet King ", stock: 0 },
  { code: "SCD0026", name: "Almohadas std", stock: 0 },
  { code: "SCD0027", name: "Fundas Almohadas lisa std ", stock: 0 },
  { code: "SCD0028", name: "Protector Almohada std cierre ", stock: 0 },
  { code: "SCD0029", name: "Almohadas King ", stock: 0 },
  { code: "SCD0030", name: "Protector almohada cierre ", stock: 0 },
  { code: "SCD0031", name: "Funda Almohada King ", stock: 0 },
  { code: "SCD0032", name: "Cortinas Frescura ", stock: 0 },
  { code: "SCD0033", name: "Cortinas Blackout ", stock: 0 },
  { code: "SCD0034", name: "Cojines decorativos", stock: 0 },
  { code: "SCD0035", name: "Forros decorativos", stock: 0 },
  
];

export const headerItems = {
  img: "https://www.selina.com/static/media/selina_logo_black.b62a0982.svg",
  navitation: [
    { name: "Instrucciones ", url: "home" },
    { name: "Inventario", url: "home" },
  ]
}; 